export const YoutubeAdapterCreator = () => {
  let canRenderInCaptionWindow = true;
  let caption;
  let captionWindow;
  let video;

  // Caption windows with auto-generated captions can't be rendered into
  const autoGeneratedCaptionWindow = document.querySelector('.ytp-caption-window-rollup');
  if (autoGeneratedCaptionWindow) {
    canRenderInCaptionWindow = false;
  }

  video = document.querySelector('video');
  captionWindow = document.querySelector('.ytp-caption-window-bottom') || document.querySelector('.caption-window');
  caption = document.querySelector('.ytp-caption-segment');
  return {
    canRenderInCaptionWindow,
    captionWindow: captionWindow ? captionWindow : null,
    captionWindowPosition: captionWindow ? captionWindow.style.cssText : null,
    captionWindowStyle: { textAlign: 'center', width: '700px' },
    captionStyle: caption ? {
      background: caption.style.background,
      backgroundColor: caption.style.backgroundColor,
      color: caption.style.color,
      fontFamily: caption.style.fontFamily,
      fontSize: caption.style.fontSize
    } : null,
    captionClassName: 'captions-text',
    video: video ? video : null
  };
}

const YoutubeAdapter = {
  root: document.body,
  uniqueSelector: '#movie_player',
  value: YoutubeAdapterCreator
}

export default YoutubeAdapter;
